# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
import enum
import numpy
import numpy.typing
import openqudit
import typing
__all__ = [
    "DirectiveOperation",
    "Instruction",
    "InstructionId",
    "InstructionReference",
    "OpCode",
    "OpKind",
    "Operation",
    "ParameterVector",
    "QuditCircuit",
    "QuditCircuitIterator",
    "Wire",
    "WireList",
    "WireListIterator",
]

@typing.final
class Instruction:
    r"""
    Python wrapper for quantum instructions.
    
    This provides a read-only view of instructions from Python, with
    access to operation codes, target wires, and parameter indices.
    """
    @property
    def op_code(self) -> OpCode:
        r"""
        Returns the operation code for this instruction.
        """
    @property
    def wires(self) -> WireList:
        r"""
        Returns the target wires for this instruction.
        """
    @property
    def params(self) -> openqudit.ParamIndices:
        r"""
        Returns the parameter indices for this instruction.
        """
    @property
    def num_params(self) -> builtins.int:
        r"""
        Returns the number of parameters for this instruction.
        """
    def __eq__(self, other: builtins.object, /) -> builtins.bool: ...
    def __hash__(self) -> builtins.int: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class InstructionId:
    r"""
    Python wrapper for `InstructionId` providing access to instruction identifiers.
    
    This wrapper allows Python code to work with instruction identifiers while
    maintaining type safety and preventing invalid construction.
    """
    @property
    def cycle(self) -> builtins.int:
        r"""
        Returns the cycle identifier component of this instruction ID.
        """
    @property
    def inner(self) -> builtins.int:
        r"""
        Returns the instruction identifier component within the cycle.
        """
    def __eq__(self, other: builtins.object, /) -> builtins.bool: ...
    def __lt__(self, other: builtins.object, /) -> builtins.bool: ...
    def __le__(self, other: builtins.object, /) -> builtins.bool: ...
    def __gt__(self, other: builtins.object, /) -> builtins.bool: ...
    def __ge__(self, other: builtins.object, /) -> builtins.bool: ...
    def __hash__(self) -> builtins.int: ...
    def __repr__(self) -> builtins.str: ...
    def __str__(self) -> builtins.str: ...

@typing.final
class InstructionReference:
    def name(self) -> builtins.str: ...
    def wires(self) -> WireList: ...
    def params(self) -> builtins.list[typing.Optional[builtins.float]]: ...
    def cycle_id(self) -> builtins.int: ...
    def cycle_index(self) -> builtins.int: ...
    def num_qudits(self) -> builtins.int: ...
    def num_dits(self) -> builtins.int: ...

@typing.final
class OpCode:
    r"""
    Python wrapper for the OpCode struct.
    
    Provides access to quantum operation code functionality from Python.
    """
    @property
    def kind(self) -> OpKind:
        r"""
        Returns the operation kind.
        """
    @property
    def id(self) -> builtins.int:
        r"""
        Returns the operation reference ID.
        """
    def __eq__(self, other: builtins.object, /) -> builtins.bool: ...
    def __lt__(self, other: builtins.object, /) -> builtins.bool: ...
    def __le__(self, other: builtins.object, /) -> builtins.bool: ...
    def __gt__(self, other: builtins.object, /) -> builtins.bool: ...
    def __ge__(self, other: builtins.object, /) -> builtins.bool: ...
    def __hash__(self) -> builtins.int: ...
    def __repr__(self) -> builtins.str: ...
    def __str__(self) -> builtins.str: ...

@typing.final
class OpKind:
    r"""
    Python wrapper for OpKind.
    """
    def __eq__(self, other: builtins.object, /) -> builtins.bool: ...
    def __lt__(self, other: builtins.object, /) -> builtins.bool: ...
    def __le__(self, other: builtins.object, /) -> builtins.bool: ...
    def __gt__(self, other: builtins.object, /) -> builtins.bool: ...
    def __ge__(self, other: builtins.object, /) -> builtins.bool: ...
    def __hash__(self) -> builtins.int: ...
    def __int__(self) -> builtins.int:
        r"""
        Get integer representation.
        """
    def __str__(self) -> builtins.str:
        r"""
        String representation.
        """
    def __repr__(self) -> builtins.str:
        r"""
        Debug representation.
        """

@typing.final
class Operation:
    def num_qudits(self) -> typing.Optional[builtins.int]: ...
    def num_params(self) -> builtins.int: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class ParameterVector:
    def assign_all(self, values: typing.Sequence[builtins.float]) -> None: ...

@typing.final
class QuditCircuit:
    @property
    def num_qudits(self) -> builtins.int:
        r"""
        Returns the number of qudits in the circuit.
        """
    @property
    def num_params(self) -> builtins.int:
        r"""
        Returns the number of parameters in the circuit.
        """
    @property
    def num_operations(self) -> builtins.int:
        r"""
        Returns the number of operations in the circuit.
        """
    @property
    def num_cycles(self) -> builtins.int:
        r"""
        Returns the number of cycles in the circuit.
        """
    @property
    def is_empty(self) -> builtins.bool: ...
    @property
    def active_qudits(self) -> builtins.list[builtins.int]: ...
    @property
    def active_dits(self) -> builtins.list[builtins.int]: ...
    @property
    def params(self) -> ParameterVector: ...
    @property
    def front(self) -> builtins.dict[Wire, InstructionId]: ...
    @property
    def rear(self) -> builtins.dict[Wire, InstructionId]: ...
    def __new__(cls, qudits: typing.Any, dits: typing.Optional[typing.Any] = None) -> QuditCircuit:
        r"""
        Creates a new QuditCircuit instance.
        
        Args:
            qudits (int | Iterable[int]): An integer specifying number of qudits
                or an iterable of qudit radices.
            dits (int | Iterable[int] | None): An integer, an iterable, or None.
                Defaults to None, which results in no classical dits.
        """
    def clone(self) -> QuditCircuit: ...
    def first_on(self, wire: Wire) -> typing.Optional[InstructionId]: ...
    def last_on(self, wire: Wire) -> typing.Optional[InstructionId]: ...
    def next(self, inst_id: InstructionId) -> builtins.dict[Wire, InstructionId]: ...
    def prev(self, inst_id: InstructionId) -> builtins.dict[Wire, InstructionId]: ...
    def kraus_ops(self, args: typing.Optional[typing.Any] = None) -> numpy.typing.NDArray[numpy.complex128]:
        r"""
        Returns the Kraus operators of the circuit as a NumPy array.
        """
    def append(self, op: typing.Any, loc: typing.Any, args: typing.Optional[typing.Sequence[builtins.float]] = None) -> InstructionReference: ...
    def cache(self, op: Operation) -> OpCode: ...
    def remove(self, inst_id: InstructionId) -> typing.Optional[Instruction]: ...
    def count(self, op_code: OpCode) -> builtins.int: ...
    def __iter__(self) -> QuditCircuitIterator: ...
    @staticmethod
    def load(path: builtins.str) -> QuditCircuit:
        r"""
        Load a circuit from a file.  The format is inferred from the file
        extension (e.g. `.qasm` or `.qasm2` selects the QASM 2.0 parser).
        """
    @staticmethod
    def loads(source: builtins.str, *, format: builtins.str = 'qasm2') -> QuditCircuit:
        r"""
        Parse a circuit from a string.
        
        Args:
            source: The source string to parse.
            format: The format name or file extension to use (default ``"qasm2"``).
        """
    def dump(self, path: builtins.str) -> None:
        r"""
        Write the circuit to a file.  The format is inferred from the file
        extension (e.g. `.qasm` or `.qasm2` selects the QASM 2.0 writer).
        """
    def dumps(self, *, format: builtins.str = 'qasm2') -> builtins.str:
        r"""
        Serialise the circuit to a string.
        
        Args:
            format: The format name or file extension to use (default ``"qasm2"``).
        """
    def __setstate__(self, state: bytes) -> None: ...
    def __getstate__(self) -> bytes: ...
    def __getnewargs__(self) -> tuple[builtins.list[builtins.int]]: ...

@typing.final
class QuditCircuitIterator:
    def __iter__(self) -> QuditCircuitIterator: ...
    def __next__(self) -> typing.Optional[InstructionReference]: ...

@typing.final
class Wire:
    r"""
    Python wrapper for the Wire struct.
    
    Provides access to quantum circuit wire functionality from Python.
    """
    @property
    def is_quantum(self) -> builtins.bool:
        r"""
        Check if this wire represents a quantum wire.
        """
    @property
    def is_classical(self) -> builtins.bool:
        r"""
        Check if this wire represents a classical wire.
        """
    @property
    def is_null(self) -> builtins.bool:
        r"""
        Check if this wire is null/invalid.
        """
    @property
    def is_valid(self) -> builtins.bool:
        r"""
        Check if this wire is valid (not null).
        """
    @property
    def index(self) -> builtins.int:
        r"""
        Get the zero-based index of the wire.
        """
    @property
    def raw_value(self) -> builtins.int:
        r"""
        Get the raw internal value of the wire.
        """
    def __eq__(self, other: builtins.object, /) -> builtins.bool: ...
    def __lt__(self, other: builtins.object, /) -> builtins.bool: ...
    def __le__(self, other: builtins.object, /) -> builtins.bool: ...
    def __gt__(self, other: builtins.object, /) -> builtins.bool: ...
    def __ge__(self, other: builtins.object, /) -> builtins.bool: ...
    def __hash__(self) -> builtins.int: ...
    @staticmethod
    def quantum(idx: builtins.int) -> Wire:
        r"""
        Create a quantum wire with the given index.
        """
    @staticmethod
    def classical(idx: builtins.int) -> Wire:
        r"""
        Create a classical wire with the given index.
        """
    @staticmethod
    def from_raw(val: builtins.int) -> Wire:
        r"""
        Create a wire from a raw isize value.
        """
    def __str__(self) -> builtins.str:
        r"""
        String representation of the wire.
        """
    def __repr__(self) -> builtins.str:
        r"""
        Representation string for the wire.
        """

@typing.final
class WireList:
    r"""
    Python wrapper for WireList
    """
    @property
    def qudits(self) -> list:
        r"""
        Get quantum wire indices as Python list
        """
    @property
    def dits(self) -> list:
        r"""
        Get classical wire indices as Python list
        """
    @property
    def num_qudits(self) -> builtins.int:
        r"""
        Get number of quantum wires
        """
    @property
    def num_dits(self) -> builtins.int:
        r"""
        Get number of classical wires
        """
    def __eq__(self, other: builtins.object, /) -> builtins.bool: ...
    def __hash__(self) -> builtins.int: ...
    @staticmethod
    def pure(indices: typing.Sequence[builtins.int]) -> WireList:
        r"""
        Create a purely quantum WireList from Python
        """
    @staticmethod
    def classical(indices: typing.Sequence[builtins.int]) -> WireList:
        r"""
        Create a purely classical WireList from Python
        """
    def __new__(cls, qudits_or_wires: typing.Any, dits: typing.Optional[typing.Sequence[builtins.int]] = None) -> WireList:
        r"""
        Create a mixed WireList from Python
        """
    def contains_qudit(self, index: builtins.int) -> builtins.bool:
        r"""
        Check if wire list contains a quantum wire
        """
    def contains_dit(self, index: builtins.int) -> builtins.bool:
        r"""
        Check if wire list contains a classical wire
        """
    def union(self, other: WireList) -> WireList:
        r"""
        Union operation
        """
    def intersect(self, other: WireList) -> WireList:
        r"""
        Intersection operation
        """
    def difference(self, other: WireList) -> WireList:
        r"""
        Difference operation
        """
    def __len__(self) -> builtins.int:
        r"""
        Python len() function - returns total number of wires
        """
    def __bool__(self) -> builtins.bool:
        r"""
        Python bool() function - empty wire lists are falsy
        """
    def __contains__(self, wire: Wire) -> builtins.bool:
        r"""
        Python 'in' operator - checks if wire exists in list
        """
    def __and__(self, other: WireList) -> WireList:
        r"""
        Python '&' operator - intersection operation
        """
    def __or__(self, other: WireList) -> WireList:
        r"""
        Python '|' operator - union operation (alternative)
        """
    def __sub__(self, other: WireList) -> WireList:
        r"""
        Python '-' operator - difference operation
        """
    def __iter__(self) -> WireListIterator:
        r"""
        Python iterator - yields Wire objects
        """
    def __str__(self) -> builtins.str:
        r"""
        Python string representation
        """
    def __repr__(self) -> builtins.str:
        r"""
        Python debug representation
        """

@typing.final
class WireListIterator:
    def __iter__(self) -> WireListIterator: ...
    def __next__(self) -> typing.Optional[Wire]: ...

@typing.final
class DirectiveOperation(enum.Enum):
    Barrier = ...

