# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
import enum
import typing
__all__ = [
    "DirectiveOperation",
    "Operation",
]

@typing.final
class Operation:
    def num_qudits(self) -> typing.Optional[builtins.int]: ...
    def num_params(self) -> builtins.int: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class DirectiveOperation(enum.Enum):
    Barrier = ...

