# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
import fractions
import numpy
import numpy.typing
import typing
__all__ = [
    "BraExpression",
    "BraSystemExpression",
    "ClassicallyControlled",
    "ComplexExpression",
    "Controlled",
    "Dagger",
    "Expression",
    "HGate",
    "IGate",
    "Invert",
    "KetExpression",
    "KetSystemExpression",
    "KrausOperatorsExpression",
    "PGate",
    "ParameterizedUnitary",
    "RXGate",
    "RXXGate",
    "RYGate",
    "RYYGate",
    "RZGate",
    "RZZGate",
    "SGate",
    "SXGate",
    "SwapGate",
    "TGate",
    "U1Gate",
    "U2Gate",
    "U3Gate",
    "UnitaryExpression",
    "UnitarySystemExpression",
    "XGate",
    "YGate",
    "ZGate",
    "ZMeasurement",
    "ZeroState",
]

@typing.final
class BraExpression:
    r"""
    A symbolic bra (row) vector expression over a qudit system.
    """
    def __new__(cls, expr: builtins.str) -> BraExpression:
        r"""
        Parses a bra expression from its string representation.
        
        # Arguments
        
        * `expr` - The textual definition of the bra expression.
        """
    def num_params(self) -> builtins.int:
        r"""
        Returns the number of free (unbound) parameters in this expression.
        """
    def name(self) -> builtins.str:
        r"""
        Returns the name assigned to this expression.
        """
    def radices(self) -> builtins.list[builtins.int]:
        r"""
        Returns the radix of each qudit that this bra acts on.
        """
    def num_qudits(self) -> builtins.int:
        r"""
        Returns the number of qudits this unitary acts on.
        """
    def is_qubit_only(self) -> builtins.bool:
        r"""
        Returns true if this unitary acts on a qubit-only system.
        """
    def is_qutrit_only(self) -> builtins.bool:
        r"""
        Returns true if this unitary acts on a qutrit-only system
        """
    def is_qudit_only(self, radix: builtins.int) -> builtins.bool:
        r"""
        Returns true if this unitary acts on a `radix`-only system
        """
    def is_homogenous(self) -> builtins.bool:
        r"""
        Returns true if this unitary acts on a homogenous system
        """
    def variables(self) -> builtins.list[builtins.str]:
        r"""
        Returns the names of the free parameters in this tree, in the order
        they are first encountered.
        """
    def elements(self) -> builtins.list[ComplexExpression]: ...
    def conjugate(self) -> BraExpression: ...
    def dimension(self) -> builtins.int:
        r"""
        Returns the total Hilbert space dimension of the underlying qudit system.
        """
    def __hash__(self) -> builtins.int:
        r"""
        Returns a hash of this expression's body and qudit structure.
        
        Mirrors Rust equality, which compares element bodies and qudit
        structure and ignores the name the expression was given.
        """
    def __eq__(self, other: BraExpression) -> builtins.bool: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class BraSystemExpression:
    r"""
    A symbolic expression representing a batched system of bra (row) vectors.
    """
    def __new__(cls, expr: builtins.str) -> BraSystemExpression:
        r"""
        Parses a bra system expression from its string representation.
        
        # Arguments
        
        * `expr` - The textual definition of the bra system expression.
        """
    def num_params(self) -> builtins.int:
        r"""
        Returns the number of free (unbound) parameters in this expression.
        """
    def name(self) -> builtins.str:
        r"""
        Returns the name assigned to this expression.
        """
    def radices(self) -> builtins.list[builtins.int]:
        r"""
        Returns the radix of each qudit that this bra system acts on.
        """
    def num_qudits(self) -> builtins.int:
        r"""
        Returns the number of qudits in the system.
        """
    def num_states(self) -> builtins.int:
        r"""
        Returns the number of individual bra states batched in this system.
        """
    def dimension(self) -> builtins.int:
        r"""
        Returns the total Hilbert space dimension of the underlying qudit system.
        """
    def variables(self) -> builtins.list[builtins.str]:
        r"""
        Returns the names of the free parameters in this tree, in the order
        they are first encountered.
        """
    def elements(self) -> builtins.list[ComplexExpression]: ...
    def conjugate(self) -> BraSystemExpression: ...
    def __hash__(self) -> builtins.int:
        r"""
        Returns a hash of this expression's body and qudit structure.
        
        Mirrors Rust equality, which compares element bodies and qudit
        structure and ignores the name the expression was given.
        """
    def __eq__(self, other: BraSystemExpression) -> builtins.bool: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class ComplexExpression:
    r"""
    A symbolic complex scalar, stored as a pair of real expression trees.
    
    This is the element type of every expression body: a `UnitaryExpression`
    over `d` qudit levels is `d * d` of these.
    """
    @property
    def real(self) -> Expression:
        r"""
        The real part of this expression.
        """
    @property
    def imag(self) -> Expression:
        r"""
        The imaginary part of this expression.
        """
    def variables(self) -> builtins.list[builtins.str]:
        r"""
        Returns the names of the free parameters in this expression, in the
        order they are first encountered.
        """
    def is_parameterized(self) -> builtins.bool:
        r"""
        Returns whether this expression references any free parameter.
        """
    def is_real(self) -> builtins.bool:
        r"""
        Returns whether the imaginary part is structurally zero.
        """
    def is_imag(self) -> builtins.bool:
        r"""
        Returns whether the real part is structurally zero and the imaginary
        part is not.
        """
    def is_cplx(self) -> builtins.bool:
        r"""
        Returns whether both parts are structurally non-zero.
        """
    def is_zero(self) -> builtins.bool:
        r"""
        Returns whether both parts are structurally equivalent to zero.
        """
    def is_one(self) -> builtins.bool:
        r"""
        Returns whether this expression is structurally equivalent to one.
        """
    def conjugate(self) -> ComplexExpression:
        r"""
        Returns the complex conjugate of this expression.
        """
    def simplify(self) -> ComplexExpression:
        r"""
        Returns an algebraically simplified version of this expression.
        """
    def differentiate(self, wrt: builtins.str) -> ComplexExpression:
        r"""
        Returns the partial derivative of this expression with respect to a
        parameter.
        
        # Arguments
        
        * `wrt` - The name of the parameter to differentiate with respect to.
        """
    def rename_variable(self, original: builtins.str, new: builtins.str) -> ComplexExpression:
        r"""
        Returns this expression with one parameter renamed.
        
        # Arguments
        
        * `original` - The current parameter name.
        * `new` - The replacement name.
        """
    def substitute(self, original: Expression, substitution: Expression) -> ComplexExpression:
        r"""
        Returns this expression with every occurrence of one subtree
        replaced by another.
        
        # Arguments
        
        * `original` - The subtree to search for.
        * `substitution` - The subtree to put in its place.
        """
    def evaluate(self, **values: typing.Any) -> builtins.complex:
        r"""
        Evaluates this expression numerically.
        
        # Arguments
        
        * `values` - A value for each free parameter, passed by name.
        """
    def __eq__(self, other: typing.Any) -> builtins.bool: ...
    def __hash__(self) -> builtins.int: ...
    def __repr__(self) -> builtins.str: ...

class Expression:
    r"""
    A node in a symbolic, real-valued scalar expression tree.
    
    Each variant is its own Python class (`Expression.Add`, `Expression.Sin`,
    ...) that subclasses `Expression`, so nodes can be inspected with
    `isinstance` or destructured with `match`. Nodes are immutable; the
    methods on this class all return new trees.
    """
    def variables(self) -> builtins.list[builtins.str]:
        r"""
        Returns the names of the free parameters in this tree, in the order
        they are first encountered.
        """
    def contains_variable(self, name: builtins.str) -> builtins.bool:
        r"""
        Returns whether this tree references the named parameter.
        
        # Arguments
        
        * `name` - The parameter name to look for.
        """
    def is_parameterized(self) -> builtins.bool:
        r"""
        Returns whether this tree references any free parameter.
        """
    def is_zero(self) -> builtins.bool:
        r"""
        Returns whether this tree is structurally equivalent to zero.
        """
    def is_one(self) -> builtins.bool:
        r"""
        Returns whether this tree is structurally equivalent to one.
        """
    def evaluate(self, **values: typing.Any) -> builtins.float:
        r"""
        Evaluates this tree numerically.
        
        # Arguments
        
        * `values` - A value for each free parameter, passed by name.
        """
    def to_float(self) -> builtins.float:
        r"""
        Returns the value of this tree as a float.
        
        # Errors
        
        Raises `ValueError` if the tree still has free parameters; use
        `evaluate` instead in that case.
        """
    def simplify(self) -> Expression:
        r"""
        Returns an algebraically simplified version of this tree.
        """
    def differentiate(self, wrt: builtins.str) -> Expression:
        r"""
        Returns the partial derivative of this tree with respect to a
        parameter.
        
        # Arguments
        
        * `wrt` - The name of the parameter to differentiate with respect to.
        """
    def substitute(self, original: Expression, substitution: Expression) -> Expression:
        r"""
        Returns this tree with every occurrence of one subtree replaced by
        another.
        
        # Arguments
        
        * `original` - The subtree to search for.
        * `substitution` - The subtree to put in its place.
        """
    def rename_variable(self, original: builtins.str, new: builtins.str) -> Expression:
        r"""
        Returns this tree with one parameter renamed.
        
        # Arguments
        
        * `original` - The current parameter name.
        * `new` - The replacement name.
        """
    def __neg__(self) -> Expression: ...
    def __add__(self, other: typing.Any) -> Expression: ...
    def __radd__(self, other: typing.Any) -> Expression: ...
    def __sub__(self, other: typing.Any) -> Expression: ...
    def __rsub__(self, other: typing.Any) -> Expression: ...
    def __mul__(self, other: typing.Any) -> Expression: ...
    def __rmul__(self, other: typing.Any) -> Expression: ...
    def __truediv__(self, other: typing.Any) -> Expression: ...
    def __rtruediv__(self, other: typing.Any) -> Expression: ...
    def __pow__(self, exponent: typing.Any, modulo: typing.Optional[typing.Any] = None) -> Expression: ...
    def __eq__(self, other: typing.Any) -> builtins.bool: ...
    def __hash__(self) -> builtins.int: ...
    def __repr__(self) -> builtins.str: ...
    def __str__(self) -> builtins.str: ...
    @typing.final
    class Pi(Expression):
        r"""
        The constant pi.
        """
        __match_args__ = ()
        def __new__(cls) -> Expression.Pi: ...
    
    @typing.final
    class Variable(Expression):
        r"""
        A free parameter, referenced by name.
        """
        __match_args__ = ("name",)
        @property
        def name(self) -> builtins.str:
            r"""
            The name of the parameter.
            """
        def __new__(cls, name: builtins.str) -> Expression.Variable: ...
    
    @typing.final
    class Constant(Expression):
        r"""
        An exact rational literal.
        
        Accepts an `int`, a `fractions.Fraction`, or a string such as
        `"1/3"`. `float` is rejected, since converting it would silently
        give up the exactness that makes structural equality and hashing
        meaningful.
        """
        __match_args__ = ("value",)
        @property
        def value(self) -> fractions.Fraction:
            r"""
            The value of the literal, as a `fractions.Fraction`.
            """
        def __new__(cls, value: fractions.Fraction | builtins.int | builtins.str) -> Expression.Constant: ...
    
    @typing.final
    class Neg(Expression):
        r"""
        Arithmetic negation of `operand`.
        """
        __match_args__ = ("operand",)
        @property
        def operand(self) -> Expression:
            r"""
            The negated subtree.
            """
        def __new__(cls, operand: Expression) -> Expression.Neg: ...
    
    @typing.final
    class Add(Expression):
        r"""
        The sum `lhs + rhs`.
        """
        __match_args__ = ("lhs", "rhs",)
        @property
        def lhs(self) -> Expression:
            r"""
            The left-hand summand.
            """
        @property
        def rhs(self) -> Expression:
            r"""
            The right-hand summand.
            """
        def __new__(cls, lhs: Expression, rhs: Expression) -> Expression.Add: ...
    
    @typing.final
    class Sub(Expression):
        r"""
        The difference `lhs - rhs`.
        """
        __match_args__ = ("lhs", "rhs",)
        @property
        def lhs(self) -> Expression:
            r"""
            The minuend.
            """
        @property
        def rhs(self) -> Expression:
            r"""
            The subtrahend.
            """
        def __new__(cls, lhs: Expression, rhs: Expression) -> Expression.Sub: ...
    
    @typing.final
    class Mul(Expression):
        r"""
        The product `lhs * rhs`.
        """
        __match_args__ = ("lhs", "rhs",)
        @property
        def lhs(self) -> Expression:
            r"""
            The left-hand factor.
            """
        @property
        def rhs(self) -> Expression:
            r"""
            The right-hand factor.
            """
        def __new__(cls, lhs: Expression, rhs: Expression) -> Expression.Mul: ...
    
    @typing.final
    class Div(Expression):
        r"""
        The quotient `lhs / rhs`.
        """
        __match_args__ = ("lhs", "rhs",)
        @property
        def lhs(self) -> Expression:
            r"""
            The dividend.
            """
        @property
        def rhs(self) -> Expression:
            r"""
            The divisor.
            """
        def __new__(cls, lhs: Expression, rhs: Expression) -> Expression.Div: ...
    
    @typing.final
    class Pow(Expression):
        r"""
        The power `base ** exponent`.
        """
        __match_args__ = ("base", "exponent",)
        @property
        def base(self) -> Expression:
            r"""
            The base.
            """
        @property
        def exponent(self) -> Expression:
            r"""
            The exponent.
            """
        def __new__(cls, base: Expression, exponent: Expression) -> Expression.Pow: ...
    
    @typing.final
    class Sqrt(Expression):
        r"""
        The square root of `operand`.
        """
        __match_args__ = ("operand",)
        @property
        def operand(self) -> Expression:
            r"""
            The radicand.
            """
        def __new__(cls, operand: Expression) -> Expression.Sqrt: ...
    
    @typing.final
    class Sin(Expression):
        r"""
        The sine of `operand`, in radians.
        """
        __match_args__ = ("operand",)
        @property
        def operand(self) -> Expression:
            r"""
            The angle.
            """
        def __new__(cls, operand: Expression) -> Expression.Sin: ...
    
    @typing.final
    class Cos(Expression):
        r"""
        The cosine of `operand`, in radians.
        """
        __match_args__ = ("operand",)
        @property
        def operand(self) -> Expression:
            r"""
            The angle.
            """
        def __new__(cls, operand: Expression) -> Expression.Cos: ...
    

@typing.final
class KetExpression:
    r"""
    A symbolic ket (column) vector expression over a qudit system.
    """
    def __new__(cls, expr: builtins.str) -> KetExpression:
        r"""
        Parses a ket expression from its string representation.
        
        # Arguments
        
        * `expr` - The textual definition of the ket expression.
        """
    @staticmethod
    def zero(radices: typing.Sequence[builtins.int]) -> KetExpression:
        r"""
        Constructs a zero ket expression over the given radices.
        
        # Arguments
        
        * `radices` - The radix of each qudit in the system.
        """
    def num_params(self) -> builtins.int:
        r"""
        Returns the number of free (unbound) parameters in this expression.
        """
    def name(self) -> builtins.str:
        r"""
        Returns the name assigned to this expression.
        """
    def radices(self) -> builtins.list[builtins.int]:
        r"""
        Returns the radix of each qudit that this ket acts on.
        """
    def num_qudits(self) -> builtins.int:
        r"""
        Returns the number of qudits this unitary acts on.
        """
    def is_qubit_only(self) -> builtins.bool:
        r"""
        Returns true if this unitary acts on a qubit-only system.
        """
    def is_qutrit_only(self) -> builtins.bool:
        r"""
        Returns true if this unitary acts on a qutrit-only system
        """
    def is_qudit_only(self, radix: builtins.int) -> builtins.bool:
        r"""
        Returns true if this unitary acts on a `radix`-only system
        """
    def is_homogenous(self) -> builtins.bool:
        r"""
        Returns true if this unitary acts on a homogenous system
        """
    def variables(self) -> builtins.list[builtins.str]:
        r"""
        Returns the names of the free parameters in this tree, in the order
        they are first encountered.
        """
    def elements(self) -> builtins.list[ComplexExpression]: ...
    def conjugate(self) -> KetExpression: ...
    def dimension(self) -> builtins.int:
        r"""
        Returns the total Hilbert space dimension of the underlying qudit system.
        """
    def __hash__(self) -> builtins.int:
        r"""
        Returns a hash of this expression's body and qudit structure.
        
        Mirrors Rust equality, which compares element bodies and qudit
        structure and ignores the name the expression was given.
        """
    def __eq__(self, other: KetExpression) -> builtins.bool: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class KetSystemExpression:
    r"""
    A symbolic expression representing a batched system of ket (column) vectors.
    """
    def __new__(cls, expr: builtins.str) -> KetSystemExpression:
        r"""
        Parses a ket system expression from its string representation.
        
        # Arguments
        
        * `expr` - The textual definition of the ket system expression.
        """
    def num_params(self) -> builtins.int:
        r"""
        Returns the number of free (unbound) parameters in this expression.
        """
    def name(self) -> builtins.str:
        r"""
        Returns the name assigned to this expression.
        """
    def radices(self) -> builtins.list[builtins.int]:
        r"""
        Returns the radix of each qudit that this ket system acts on.
        """
    def num_qudits(self) -> builtins.int:
        r"""
        Returns the number of qudits in the system.
        """
    def num_states(self) -> builtins.int:
        r"""
        Returns the number of individual ket states batched in this system.
        """
    def dimension(self) -> builtins.int:
        r"""
        Returns the total Hilbert space dimension of the underlying qudit system.
        """
    def variables(self) -> builtins.list[builtins.str]:
        r"""
        Returns the names of the free parameters in this tree, in the order
        they are first encountered.
        """
    def elements(self) -> builtins.list[ComplexExpression]: ...
    def conjugate(self) -> KetSystemExpression: ...
    def __hash__(self) -> builtins.int:
        r"""
        Returns a hash of this expression's body and qudit structure.
        
        Mirrors Rust equality, which compares element bodies and qudit
        structure and ignores the name the expression was given.
        """
    def __eq__(self, other: KetSystemExpression) -> builtins.bool: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class KrausOperatorsExpression:
    r"""
    A symbolic expression representing a set of Kraus operators.
    """
    def __new__(cls, expr: builtins.str) -> KrausOperatorsExpression:
        r"""
        Parses a Kraus operators expression from its string representation.
        
        # Arguments
        
        * `expr` - The textual definition of the Kraus operators expression.
        """
    def num_params(self) -> builtins.int:
        r"""
        Returns the number of free (unbound) parameters in this expression.
        """
    def name(self) -> builtins.str:
        r"""
        Returns the name assigned to this expression.
        """
    def input_radices(self) -> builtins.list[builtins.int]:
        r"""
        Returns the radix of each qudit acted on by these Kraus operators.
        """
    def output_radices(self) -> builtins.list[builtins.int]: ...
    def num_qudits(self) -> builtins.int:
        r"""
        Returns the number of qudits acted on. Panics if the input and output
        radices of the Kraus operators differ.
        """
    def num_operators(self) -> builtins.int:
        r"""
        Returns the number of Kraus operators in this set.
        """
    def dimension(self) -> builtins.int:
        r"""
        Returns the Hilbert space dimension each Kraus operator acts on.
        """
    def variables(self) -> builtins.list[builtins.str]:
        r"""
        Returns the names of the free parameters in this tree, in the order
        they are first encountered.
        """
    def elements(self) -> builtins.list[ComplexExpression]: ...
    def conjugate(self) -> KrausOperatorsExpression: ...
    def __hash__(self) -> builtins.int:
        r"""
        Returns a hash of this expression's body and qudit structure.
        
        Mirrors Rust equality, which compares element bodies and qudit
        structure and ignores the name the expression was given.
        """
    def __eq__(self, other: KrausOperatorsExpression) -> builtins.bool: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class UnitaryExpression:
    r"""
    A symbolic, parameterized expression representing a unitary matrix.
    """
    def __new__(cls, expr: builtins.str) -> UnitaryExpression:
        r"""
        Parses a unitary expression from its string representation.
        
        # Arguments
        
        * `expr` - The textual definition of the unitary expression.
        """
    @staticmethod
    def identity(name: builtins.str, radices: typing.Sequence[builtins.int]) -> UnitaryExpression:
        r"""
        Constructs an identity unitary expression over the given radices.
        
        # Arguments
        
        * `name` - The name to assign to the resulting expression.
        * `radices` - The radix of each qudit in the system.
        """
    def __call__(self, *args: typing.Any) -> numpy.typing.NDArray[numpy.complex128]:
        r"""
        Evaluates this expression at the given parameter values and returns
        the resulting unitary matrix as a NumPy array.
        
        # Arguments
        
        * `args` - The real-valued parameters to substitute into the expression,
          in the same order as `variables()`.
        """
    def gradient(self, *args: typing.Any) -> numpy.typing.NDArray[numpy.complex128]:
        r"""
        Evaluates the matrix-by-vector derivative of this expression at the
        given parameter values.
        
        Returns a NumPy array of shape `(num_params, dim, dim)`, where the
        `k`-th entry along the first axis is the elementwise partial
        derivative of the unitary matrix with respect to the `k`-th
        parameter, in the same order as `variables()`.
        
        # Arguments
        
        * `args` - The real-valued parameters to substitute into the expression,
          in the same order as `variables()`.
        """
    def num_params(self) -> builtins.int:
        r"""
        Returns the number of free (unbound) parameters in this expression.
        """
    def name(self) -> builtins.str:
        r"""
        Returns the name assigned to this expression.
        """
    def radices(self) -> builtins.list[builtins.int]:
        r"""
        Returns the radix of each qudit that this unitary acts on.
        """
    def num_qudits(self) -> builtins.int:
        r"""
        Returns the number of qudits this unitary acts on.
        """
    def is_qubit_only(self) -> builtins.bool:
        r"""
        Returns true if this unitary acts on a qubit-only system.
        """
    def is_qutrit_only(self) -> builtins.bool:
        r"""
        Returns true if this unitary acts on a qutrit-only system
        """
    def is_qudit_only(self, radix: builtins.int) -> builtins.bool:
        r"""
        Returns true if this unitary acts on a `radix`-only system
        """
    def is_homogenous(self) -> builtins.bool:
        r"""
        Returns true if this unitary acts on a homogenous system
        """
    def dimension(self) -> builtins.int:
        r"""
        Returns the total Hilbert space dimension of the underlying qudit system.
        """
    def qasm_name(self) -> typing.Optional[builtins.str]:
        r"""
        Returns the canonical OpenQASM 2.0 (`qelib1.inc`) gate name for this
        expression (e.g. `"rz"`, `"cx"`), or `None` if it has no fixed QASM
        2.0 equivalent, such as an arbitrary or custom unitary.
        """
    def transpose(self) -> UnitaryExpression:
        r"""
        Return this unitary expression, transposed.
        """
    def dagger(self) -> UnitaryExpression:
        r"""
        Conjugate-transposes (Hermitian adjoint) this unitary expression in place.
        """
    def variables(self) -> builtins.list[builtins.str]:
        r"""
        Returns the names of the free parameters in this tree, in the order
        they are first encountered.
        """
    def elements(self) -> builtins.list[ComplexExpression]: ...
    def conjugate(self) -> UnitaryExpression: ...
    def otimes(self, other: UnitaryExpression) -> UnitaryExpression:
        r"""
        Computes the tensor (Kronecker) product of this expression with `other`,
        returning a new expression over the combined qudit system.
        
        # Arguments
        
        * `other` - The unitary expression to tensor with this one.
        """
    def dot(self, other: UnitaryExpression) -> UnitaryExpression:
        r"""
        Computes the matrix product of this expression with `other`,
        returning a new expression.
        
        # Arguments
        
        * `other` - The unitary expression to multiply with this one.
        """
    def embed(self, sub_matrix: UnitaryExpression, top_left_row_idx: builtins.int, top_left_col_idx: builtins.int) -> UnitaryExpression:
        r"""
        Embeds `sub_matrix` into this expression's matrix in place, placing its
        top-left corner at the given row and column index.
        
        # Arguments
        
        * `sub_matrix` - The smaller unitary expression to embed.
        * `top_left_row_idx` - Row index at which to place the sub-matrix.
        * `top_left_col_idx` - Column index at which to place the sub-matrix.
        """
    def __hash__(self) -> builtins.int:
        r"""
        Returns a hash of this expression's body and qudit structure.
        
        Mirrors Rust equality, which compares element bodies and qudit
        structure and ignores the name the expression was given.
        """
    def __eq__(self, other: UnitaryExpression) -> builtins.bool: ...
    def __repr__(self) -> builtins.str: ...
    def __matmul__(self, other: UnitaryExpression) -> UnitaryExpression: ...
    def __setstate__(self, state: bytes) -> None: ...
    def __getstate__(self) -> bytes: ...
    def __getnewargs__(self) -> tuple[builtins.str]: ...

@typing.final
class UnitarySystemExpression:
    r"""
    A symbolic expression representing a batched system of unitary matrices.
    """
    def __new__(cls, expr: builtins.str) -> UnitarySystemExpression:
        r"""
        Parses a unitary system expression from its string representation.
        
        # Arguments
        
        * `expr` - The textual definition of the unitary system expression.
        """
    def num_params(self) -> builtins.int:
        r"""
        Returns the number of free (unbound) parameters in this expression.
        """
    def name(self) -> builtins.str:
        r"""
        Returns the name assigned to this expression.
        """
    def radices(self) -> builtins.list[builtins.int]:
        r"""
        Returns the radix of each qudit that this unitary system acts on.
        """
    def num_qudits(self) -> builtins.int:
        r"""
        Returns the number of qudits in the system.
        """
    def num_unitaries(self) -> builtins.int:
        r"""
        Returns the number of individual unitaries batched in this system.
        """
    def dimension(self) -> builtins.int:
        r"""
        Returns the Hilbert space dimension of each unitary in the system.
        """
    def __hash__(self) -> builtins.int:
        r"""
        Returns a hash of this expression's body and qudit structure.
        
        Mirrors Rust equality, which compares element bodies and qudit
        structure and ignores the name the expression was given.
        """
    def __eq__(self, other: UnitarySystemExpression) -> builtins.bool: ...
    def __repr__(self) -> builtins.str: ...

def ClassicallyControlled(expr: UnitaryExpression, control_radices: builtins.int | typing.Sequence[builtins.int] = [2], control_levels: typing.Optional[typing.Sequence[typing.Sequence[builtins.int]]] = None) -> UnitarySystemExpression: ...

def Controlled(expr: UnitaryExpression, control_radices: builtins.int | typing.Sequence[builtins.int] = [2], control_levels: typing.Optional[typing.Sequence[typing.Sequence[builtins.int]]] = None) -> UnitaryExpression:
    r"""
    An arbitrary controlled gate.
    
    Given any gate, ControlledGate can add control qudits.
    
    A controlled gate adds arbitrarily controls, and is generalized
    for qudit or even mixed-qudit representation.
    
    A controlled gate has a circuit structure as follows:
    
    ```text
        controls ----/----■----
                          |
                         .-.
        targets  ----/---|G|---
                         '-'
    ```
    
    Where $G$ is the gate being controlled.
    
    To calculate the unitary for a controlled gate, given the unitary of
    the gate being controlled, we can use the following equation:
    
    $$U_{control} = P_i \otimes I + P_c \otimes G$$
    
    Where $P_i$ is the projection matrix for the states that don't
    activate the gate, $P_c$ is the projection matrix for the
    states that do activate the gate, $I$ is the identity matrix
    of dimension equal to the gate being controlled, and $G$ is
    the unitary matrix of the gate being controlled.
    
    In the simple case of a normal qubit CNOT ($G = X$), $P_i$ and $P_c$
    are defined as follows:
    
    $$
        P_i = \ket{0}\bra{0}
        P_c = \ket{1}\bra{1}
    $$
    
    This is because the $\ket{0}$ state is the state that doesn't
    activate the gate, and the $\ket{1}$ state is the state that
    does activate the gate.
    
    We can also decide to invert this, and have the $\ket{0}$
    state activate the gate, and the $\ket{1}$ state not activate
    the gate. This is equivalent to swapping $P_i$ and $P_c$,
    and usually drawn diagrammatically as follows:
    
    ```text
        controls ----/----□----
                          |
                         .-.
        targets  ----/---|G|---
                         '-'
    ```
    
    When we add more controls the projection matrices become more complex,
    but the basic idea stays the same: we have a projection matrix for
    the states that activate the gate, and a projection matrix for the
    states that don't activate the gate. As in the case of a toffoli gate,
    the projection matrices are defined as follows:
    
    $$
        P_i = \ket{00}\bra{00} + \ket{01}\bra{01} + \ket{10}\bra{10}
        P_c = \ket{11}\bra{11}
    $$
    
    This is because the $\ket{00}$, $\ket{01}$, and
    $\ket{10}$ states are the states that don't activate the
    gate, and the $\ket{11}$ state is the state that does
    activate the gate.
    
    With qudits, we have more states and as such, more complex
    projection matrices; however, the basic idea is the same.
    For example, a qutrit controlled-not gate that is activated by
    the $\ket{2}$ state and not activated by the $\ket{0}$
    and $\ket{1}$ states is defined as follows:
    
    $$
        P_i = \ket{0}\bra{0} + \ket{1}\bra{1}
        P_c = \ket{2}\bra{2}
    $$
    
    One interesting concept with qudits is that we can have multiple
    active control levels. For example, a qutrit controlled-not gate that
    is activated by the $\ket{1}$ and $\ket{2}$ states
    and not activated by the $\ket{0}$ state is defined similarly
    as follows:
    
    $$
        P_i = \ket{0}\bra{0}
        P_c = \ket{1}\bra{1} + \ket{2}\bra{2}
    $$
    
    Note that we can always define $P_i$ simply from $P_c$:
    
    $$P_i = I_p - P_c$$
    
    Where $I_p$ is the identity matrix of dimension equal to the
    dimension of the control qudits. This leaves us with out final
    equation:
    
    
    $$U_{control} = (I_p - P_c) \otimes I + P_c \otimes G$$
    
    If, G is a unitary-valued function of real parameters, then the
    gradient of the controlled gate simply discards the constant half
    of the equation:
    
    $$
        \frac{\partial U_{control}}{\partial \theta} =
            P_c \otimes \frac{\partial G}{\partial \theta}
    $$
    
    # Arguments
    
    * `expr` - The gate to control.
    
    * `control_radixes` - The number of levels for each control qudit.
    
    * `control_levels` - The levels of the control qudits that activate the
      gate. If more than one level is selected, the subspace spanned by the
      levels acts as a control subspace. If all levels are selected for a
      given qudit, the operation is equivalent to the original gate without
      controls.
    # Panics
    
    * If `control_radixes` and `control_levels` have different lengths.
    
    * If `control_levels` contains an empty level.
    
    * If any level in `control_levels` is greater than or equal to the
      corresponding radix in `control_radixes`.
    
    * If any level in `control_levels` is not unique.
    """

def Dagger(expr: UnitaryExpression) -> UnitaryExpression:
    r"""
    Apply the conjugate transpose (dagger / adjoint) to a unitary expression.
    
    For any unitary $U$ this produces $U^\dagger$. Use this transformer to
    obtain the inverse of any gate without defining a separate gate function;
    for example, `Dagger(SGate(2))` gives $S^\dagger$ and `Dagger(TGate(2))`
    gives $T^\dagger$.
    """

def HGate(radix: builtins.int = 2) -> UnitaryExpression:
    r"""
    The one-qudit Hadamard gate. This is a Clifford/Weyl-Heisenberg gate.
    
    The qubit (radix = 2) Hadamard gate is given by the following matrix:
    
    $$
    \begin{pmatrix}
        \frac{\sqrt{2}}{2} & \frac{\sqrt{2}}{2} \\\\
        \frac{\sqrt{2}}{2} & -\frac{\sqrt{2}}{2} \\\\
    \end{pmatrix}
    $$
    
    However, generally it is given by the following formula:
    
    $$
    H = \frac{1}{\sqrt{d}} \sum_{ij} \omega^{ij} \ket{i}\bra{j}
    $$
    
    where
    
    $$
    \omega = \exp\Big(\frac{2\pi i}{d}\Big)
    $$
    
    and $d$ is the number of levels (2 levels is a qubit, 3 levels is a qutrit,
    etc.)
    
    References:
    - <https://www.frontiersin.org/articles/10.3389/fphy.2020.589504/full>
    - <https://pubs.aip.org/aip/jmp/article-abstract/56/3/032202/763827>
    - <https://arxiv.org/pdf/1701.07902.pdf>
    """

def IGate(radix: builtins.int = 2) -> UnitaryExpression:
    r"""
    The identity or no-op gate.
    """

def Invert(expr: UnitaryExpression) -> UnitaryExpression:
    r"""
    Invert an expression
    """

def PGate(radix: builtins.int = 2) -> UnitaryExpression:
    r"""
    The single-qudit phase gate.
    
    The common qubit phase gate is given by the following matrix:
    
    $$
    \begin{pmatrix}
        1 & 0 \\\\
        0 & \exp({i\theta}) \\\\
    \end{pmatrix}
    $$
    
    The qutrit phase gate has two parameterized relative phases:
    
    $$
    \begin{pmatrix}
        1 & 0 & 0 \\\\
        0 & \exp({i\theta_0}) & 0 \\\\
       0 & 0 & \exp({i\theta_1}) \\\\
    \end{pmatrix}
    $$
    
    The d-level phase gate has d-1 parameterized relative phases. This
    gate is Clifford iff all of the relative phases are powers of roots
    of unity.
    
    References:
    - <https://www.nature.com/articles/s41467-022-34851-z>
    - <https://arxiv.org/pdf/2204.13681.pdf>
    """

def ParameterizedUnitary(radices: builtins.int | typing.Sequence[builtins.int] = [2]) -> UnitaryExpression:
    r"""
    Generates a fully parameterized unitary expression
    
    References:
    - de Guise, Hubert, Olivia Di Matteo, and Luis L. Sánchez-Soto.
      "Simple factorization of unitary transformations."
      Physical Review A 97.2 (2018): 022328.
    """

def RXGate() -> UnitaryExpression:
    r"""
    The single-qubit RX gate (rotation around the X-axis).
    
    $$
    RX(\theta) = \begin{pmatrix} \cos(\theta/2) & -i\sin(\theta/2) \\\\ -i\sin(\theta/2) & \cos(\theta/2) \end{pmatrix}
    $$
    """

def RXXGate() -> UnitaryExpression:
    r"""
    The two-qubit RXX gate (Ising XX coupling).
    
    $$
    RXX(\theta) = e^{-i\theta/2 \, X \otimes X} =
    \begin{pmatrix}
        \cos(\theta/2) & 0 & 0 & -i\sin(\theta/2) \\\\
        0 & \cos(\theta/2) & -i\sin(\theta/2) & 0 \\\\
        0 & -i\sin(\theta/2) & \cos(\theta/2) & 0 \\\\
        -i\sin(\theta/2) & 0 & 0 & \cos(\theta/2)
    \end{pmatrix}
    $$
    """

def RYGate() -> UnitaryExpression:
    r"""
    The single-qubit RY gate (rotation around the Y-axis).
    
    $$
    RY(\theta) = \begin{pmatrix} \cos(\theta/2) & -\sin(\theta/2) \\\\ \sin(\theta/2) & \cos(\theta/2) \end{pmatrix}
    $$
    """

def RYYGate() -> UnitaryExpression:
    r"""
    The two-qubit RYY gate (Ising YY coupling).
    
    $$
    RYY(\theta) = e^{-i\theta/2 \, Y \otimes Y} =
    \begin{pmatrix}
        \cos(\theta/2) & 0 & 0 & i\sin(\theta/2) \\\\
        0 & \cos(\theta/2) & -i\sin(\theta/2) & 0 \\\\
        0 & -i\sin(\theta/2) & \cos(\theta/2) & 0 \\\\
        i\sin(\theta/2) & 0 & 0 & \cos(\theta/2)
    \end{pmatrix}
    $$
    """

def RZGate() -> UnitaryExpression:
    r"""
    The single-qubit RZ gate (rotation around the Z-axis).
    
    $$
    RZ(\theta) = \begin{pmatrix} e^{-i\theta/2} & 0 \\\\ 0 & e^{i\theta/2} \end{pmatrix}
    $$
    """

def RZZGate() -> UnitaryExpression:
    r"""
    The two-qubit RZZ gate (Ising ZZ coupling).
    
    $$
    RZZ(\theta) = e^{-i\theta/2 \, Z \otimes Z} =
    \begin{pmatrix}
        e^{-i\theta/2} & 0 & 0 & 0 \\\\
        0 & e^{i\theta/2} & 0 & 0 \\\\
        0 & 0 & e^{i\theta/2} & 0 \\\\
        0 & 0 & 0 & e^{-i\theta/2}
    \end{pmatrix}
    $$
    """

def SGate(radix: builtins.int = 2) -> UnitaryExpression:
    r"""
    The one-qudit S gate (Clifford level 2).
    
    Defined as:
    
    $$
    S|k\rangle = e^{i\pi k^2 / d}|k\rangle
    $$
    
    where $d$ is the number of levels. For qubits ($d = 2$) this reproduces
    the standard S gate $S = \text{diag}(1, i)$. Note that $S^2 = T^2\cdot T^2$
    and $T^2 = S$, i.e. the T gate defined below is the square root of S.
    
    This gate is Clifford (level 2 of the Clifford hierarchy): conjugation
    by S maps every Pauli to another Pauli.
    
    For qutrits ($d = 3$), up to the global-phase convention of Yeh & van de
    Wetering (ζ⁸ with ζ = e^{2πi/9}), this agrees with their Definition 3.
    
    References:
    - Gheorghiu, V. (2014). Standard form of qudit stabilizer groups.
      Physics Letters A, 378(30–31), 2016–2021.
    - Yeh, L. & van de Wetering, J. (2023). Completeness of the ZH-calculus.
    """

def SXGate() -> UnitaryExpression:
    r"""
    The single-qubit SX gate (square-root of X / square-root of Pauli-X).
    
    $$
    SX = \sqrt{X} = \frac{1}{2}\begin{pmatrix} 1+i & 1-i \\\\ 1-i & 1+i \end{pmatrix}
    $$
    
    Note: a qudit generalization of this gate as $X^{1/2}$ is mathematically
    well-defined but its matrix entries involve geometric sums with non-integer
    exponents that do not reduce to a simple closed-form expression in QGL.
    """

def SwapGate(radix: builtins.int = 2) -> UnitaryExpression:
    r"""
    The qudit swap gate. This is a two-qudit Clifford/Weyl-Heisenberg gate
    that swaps the state of two qudits.
    
    The qubit (radix = 2) version is given by the following matrix:
    
    $$
    \begin{pmatrix}
        1 & 0 & 0 & 0 \\\\
        0 & 0 & 1 & 0 \\\\
        0 & 1 & 0 & 0 \\\\
        0 & 0 & 0 & 1 \\\\
    \end{pmatrix}
    $$
    
    The qutrit (radix = 3) version is given by the following matrix:
    
    $$
    \begin{pmatrix}
        1 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 \\\\
        0 & 0 & 0 & 1 & 0 & 0 & 0 & 0 & 0 \\\\
        0 & 0 & 0 & 0 & 0 & 0 & 1 & 0 & 0 \\\\
        0 & 1 & 0 & 0 & 0 & 0 & 0 & 0 & 0 \\\\
        0 & 0 & 0 & 0 & 1 & 0 & 0 & 0 & 0 \\\\
        0 & 0 & 0 & 0 & 0 & 0 & 0 & 1 & 0 \\\\
        0 & 0 & 1 & 0 & 0 & 0 & 0 & 0 & 0 \\\\
        0 & 0 & 0 & 0 & 0 & 1 & 0 & 0 & 0 \\\\
        0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 1 \\\\
    \end{pmatrix}
    $$
    
    However, generally it is given by the following formula:
    
    $$
    SWAP_d = \sum_{a, b} \ket{ab}\bra{ba}
    $$
    
    where $d$ is the number of levels (2 levels is a qubit, 3 levels is a
    qutrit, etc.)
    
    References:
    - <https://link.springer.com/article/10.1007/s11128-013-0621-x>
    - <https://arxiv.org/pdf/1105.5485.pdf>
    """

def TGate(radix: builtins.int = 2) -> UnitaryExpression:
    r"""
    The one-qudit T gate (Clifford level 3).
    
    Defined as the square root of the S gate:
    
    $$
    T|k\rangle = e^{i\pi k^2 / (2d)}|k\rangle
    $$
    
    so that $T^2 = S$. For qubits ($d = 2$) this reproduces the standard
    T gate $T = \text{diag}(1,\, e^{i\pi/4})$. For qutrits ($d = 3$),
    with ζ = e^{2πi/9}, this gives $T = \text{diag}(1, e^{i\pi/6}, e^{2i\pi/3})$;
    the Yeh–van de Wetering convention $T = \text{diag}(1, \zeta, \zeta^8)$
    (Definition 8 ibid.) differs by a global phase, and both are in level 3
    of the Clifford hierarchy.
    
    The T gate is the standard resource gate for universal quantum computation
    beyond the Clifford group: it can be injected via magic states and its
    magic states are distillable.
    
    References:
    - Howard, M. & Vala, J. (2012). Qudit versions of the qubit π/8 gate.
      Physical Review A, 86(2), 022316.
    - Cui, S. X., Gottesman, D. & Krishna, A. (2017). Diagonal gates in the
      Clifford hierarchy. Physical Review A, 95(1), 012329.
    """

def U1Gate() -> UnitaryExpression:
    r"""
    The single-qubit U1 gate (phase gate up to global phase).
    
    $$
    U1(\lambda) = \begin{pmatrix} 1 & 0 \\\\ 0 & e^{i\lambda} \end{pmatrix}
    $$
    """

def U2Gate() -> UnitaryExpression:
    r"""
    The single-qubit U2 gate.
    
    $$
    U2(\phi, \lambda) = \frac{1}{\sqrt{2}}
    \begin{pmatrix} 1 & -e^{i\lambda} \\\\ e^{i\phi} & e^{i(\phi+\lambda)} \end{pmatrix}
    $$
    """

def U3Gate() -> UnitaryExpression: ...

def XGate(radix: builtins.int = 2) -> UnitaryExpression:
    r"""
    The one-qudit shift (X) gate. This is a Weyl-Heisenberg gate.
    
    This gate shifts the state of a qudit up by one level modulo. For
    example, the shift gate on a qubit is the Pauli-X gate. The shift
    gate on a qutrit is the following matrix:
    
    $$
    \begin{pmatrix}
        0 & 0 & 1 \\\\
        1 & 0 & 0 \\\\
        0 & 1 & 0 \\\\
    \end{pmatrix}
    $$
    
    The shift gate is generally given by the following formula:
    
    $$
    \begin{equation}
        X = \sum_a |a + 1 mod d ><a|
    \end{equation}
    $$
    
    where d is the number of levels (2 levels is a qubit, 3 levels is
    a qutrit, etc.)
    
    References:
        - <https://arxiv.org/pdf/2302.07966.pdf>
    """

def YGate(radix: builtins.int = 2) -> UnitaryExpression:
    r"""
    The one-qudit Y gate. This is a Weyl-Heisenberg gate.
    
    Defined as:
    
    $$
    Y = \omega^{(d-1)/2} X Z
    $$
    
    where $\omega = e^{2\pi i / d}$, $X$ is the shift gate, and $Z$ is the
    clock gate. This choice of global phase is the natural qudit generalization
    of the Pauli Y gate: for $d = 2$ it reproduces
    
    $$
    Y = \begin{pmatrix} 0 & -i \\\\ i & 0 \end{pmatrix}
    $$
    
    In general the non-zero entry at row $(j+1 \bmod d)$, column $j$ is
    $\omega^{(d-1)/2} \cdot \omega^{j} = e^{2\pi i (2j + d - 1)/(2d)}$.
    """

def ZGate(radix: builtins.int = 2) -> UnitaryExpression:
    r"""
    The one-qudit clock (Z) gate. This is a Weyl-Heisenberg gate.
    
    This gate shifts the state of a qudit up by one level modulo. For
    example, the clock gate on a qubit is the Pauli-Z gate. The clock
    gate on a qutrit is the following matrix:
    
    $$
    \begin{pmatrix}
        1 & 0 & 0 \\\\
        0 & e^{\frac{2\pi i}{3} & 0 \\\\
        0 & 0 & e^{\frac{4\pi i}{3} \\\\
    \end{pmatrix}
    $$
    
    The clock gate is generally given by the following formula:
    
    $$
    \begin{equation}
        X = \sum_a e^{\frac{2a\pi i}{d}|a><a|
    \end{equation}
    $$
    
    where d is the number of levels (2 levels is a qubit, 3 levels is
    a qutrit, etc.)
    
    References:
        - <https://arxiv.org/pdf/2302.07966.pdf>
    """

def ZMeasurement(radix: builtins.int = 2) -> BraSystemExpression:
    r"""
    A terminating z-basis measurement for a qudit.
    """

def ZeroState(radix: builtins.int = 2) -> KetExpression:
    r"""
    Creates a zero-state ket expression with the specified radix.
    """

